### ISSUE TITLE
Instructions for SOLARPI_SECRET env variable missing

### ISSUE THREAD

**Issue by mjpieters** [Tafkas/solarpi#6]
The [old README.rst](https://github.com/Tafkas/solarpi/blob/a06af10239a48097b8a2f3709f6409610190d84e/README.rst) documenation included the text:

```
First, set your app's secret key as an environment variable. For example, example add the following to ``.bashrc`` or ``.bash_profile``.

.. code-block:: bash

    export SOLARPI_SECRET = 'something-really-secret'
```

The newer Markdown version doesn't, and it is [causing issues with people trying out this project](https://stackoverflow.com/questions/53261155/raise-keyerrorkey-keyerror-secret-key-with-flask-on-production-settings); they get a traceback that is not necessarily understandable to non-Python, non-Flask developers:

```
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    from solarpi.app import create_app
  File "/home/amani/Desktop/new/solarpi/solarpi/app.py", line 10, in <module>
    from solarpi.settings import ProdConfig
  File "/home/amani/Desktop/new/solarpi/solarpi/settings.py", line 7, in <module>
    class Config(object):
  File "/home/amani/Desktop/new/solarpi/solarpi/settings.py", line 9, in Config
    SECRET_KEY = os_env['SOLARPI_SECRET']
  File "/home/amani/Desktop/new/.venv/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'SOLARPI_SECRET'
```

Please update the new README to include the env var instructions.

**Comment by Amanimasila** [comment]
Hello have tried to follow the old readme steps 

I started by creating a .bash_profile

then added , 
    export SOLARPI_SECRET = 'SOLARPI_SECRET'

when I save and try to run the following;

python manage.py db init
python manage.py db migrate
python manage.py db upgrade
python manage.py server

they are giving me the same error 

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    from solarpi.app import create_app
  File "/home/amani/Desktop/new/solarpi/solarpi/app.py", line 10, in <module>
    from solarpi.settings import ProdConfig
  File "/home/amani/Desktop/new/solarpi/solarpi/settings.py", line 7, in <module>
    class Config(object):
  File "/home/amani/Desktop/new/solarpi/solarpi/settings.py", line 9, in Config
    SECRET_KEY = os_env['SOLARPI_SECRET']
  File "/home/amani/Desktop/new/.venv/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'SOLARPI_SECRET'

**Comment by globalepub** [comment]
whe run the server
  $ (.venv) python manage.py server 

-- python2
NameError : name 'ModuleNotFoundError' is not defined  

-- python3
ImportError: No module named 'flask.ext'
